version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    #  - KC_HOSTNAME=keycloak
    # volumes:
    #   - ./data:/opt/keycloak/data
    #restart: always
    command:
     - start-dev
