version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespw
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql